"""fix the username column name in admins table

Revision ID: 352734526b98
Revises: f30a7f9f860a
Create Date: 2024-09-01 00:42:44.576436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352734526b98'
down_revision = 'f30a7f9f860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_constraint('admins_usename_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('usename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usename', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admins_usename_key', ['usename'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
