"""try to create order_product model

Revision ID: de5a8075c7a2
Revises: 352734526b98
Create Date: 2024-09-08 20:36:51.256482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5a8075c7a2'
down_revision = '352734526b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE order_product SET price = 0 WHERE price IS NULL')
#     with op.batch_alter_table('order_product', schema=None) as batch_op:
#         batch_op.alter_column('quantity',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#         batch_op.alter_column('price',
#                existing_type=sa.INTEGER(),
#                type_=sa.Float(),
#                nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'price',
                existing_type=sa.Float(),
                nullable=False)
#     with op.batch_alter_table('order_product', schema=None) as batch_op:
#         batch_op.alter_column('price',
#                existing_type=sa.Float(),
#                type_=sa.INTEGER(),
#                nullable=True)
#         batch_op.alter_column('quantity',
#                existing_type=sa.INTEGER(),
#                nullable=True)

    # ### end Alembic commands ###
