"""correct spell of suburb column in user model

Revision ID: f0622e10d2d9
Revises: facca3e8b84a
Create Date: 2024-08-03 21:09:27.193207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0622e10d2d9'
down_revision = 'facca3e8b84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suburb', sa.String(), nullable=True))
        batch_op.drop_column('suburd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suburd', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('suburb')

    # ### end Alembic commands ###
