"""adding suburb column to user model

Revision ID: facca3e8b84a
Revises: 23f294743114
Create Date: 2024-08-03 21:07:35.347071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facca3e8b84a'
down_revision = '23f294743114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suburd', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suburd')

    # ### end Alembic commands ###
